Implement register
zinza-academy/nextjs-uynpn pull request #9
Opened 2024-06-27 09:43 UTC by phamngocuyn

2024-06-28 03:58 UTC, hungnp194 requested changes

2024-06-28 03:58 UTC, hungnp194 commented on nextjs-uynpn/src/app/component/form-auth/RegisterForm.tsx
> +  });
Thiếu default value https://react-hook-form.com/faqs#Whyisdefaultvaluenotchangingcorrectlywithternaryoperator

2024-06-28 03:58 UTC, hungnp194 commented on nextjs-uynpn/src/app/component/form-auth/RegisterForm.tsx
> +                  <MenuItem key={district.id} value={district.name}>{district.name}</MenuItem>
dùng id làm value

2024-06-28 08:24 UTC, hungnp194 requested changes

2024-06-28 08:24 UTC, hungnp194 commented on nextjs-uynpn/src/app/component/form-auth/RegisterForm.tsx
> +};
không nên defined type dùng map thế này, thêm 1 field province_id vào

2024-06-28 08:24 UTC, hungnp194 commented on nextjs-uynpn/src/app/component/form-auth/RegisterForm.tsx
> +    { id: 131, name: 'Phường 1' },
tương tự

2024-06-28 08:24 UTC, hungnp194 commented on nextjs-uynpn/src/app/component/form-auth/RegisterForm.tsx
> +      ward: '',
value không khớp với type?

2024-07-02 04:07 UTC, hungnp-zinza approved these changes

2024-07-02 04:07 UTC, merged